{% set name = "pymapd" %}
{% set version = "0.11.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8a46d84296417b9ed43d31c9cb30ea932569790f29c4955f70dd99dd421424db

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install --no-deps --ignore-installed . -vvv"

requirements:
  host:
    - python >=3
    - pip
    - setuptools_scm
    - numpy >=1.16
    - pyarrow >=0.10
  run:
    - python >=3
    - setuptools
    - {{ pin_compatible('numpy') }}
    - pyarrow >=0.10,<0.13
    - pandas >=0.24
    - six
    - sqlalchemy >=1.3
    - thrift 0.11.*

test:
  imports:
    - pymapd
    - mapd

about:
  home: http://github.com/omnisci/pymapd
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.md
  summary: 'A python DB API 2 compatible client for mapd.'
  description: |
    A python DB API 2 compatible client for mapd.
  doc_url: https://pymapd.readthedocs.io
  dev_url: https://github.com/omnisci/pymapd

extra:
  recipe-maintainers:
    - TomAugspurger
    - andrewseidl
    - randyzwitch
    - xhochy
    - xmnlab
