{% set name = "pymapd" %}
{% set version = "0.25.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 26426b06716caa3d6b2fe3351dd1aaa23f633203c5d4e02dbc1e4388eabc646a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed . -vvv

requirements:
  host:
    - python >=3.7,<3.9
    - pip
    - setuptools_scm
    - numpy
    - pyarrow 0.17.*
    - packaging >=20.0
    - rbc
  run:
    - python >=3.7,<3.9
    - setuptools
    - numba >=0.49  # keep consistency with cudf 0.15
    - {{ pin_compatible('numpy') }}
    - pyarrow 0.17.*
    - pandas >=1.0,<1.2.0dev0  # keep consistency with cudf 0.15
    - shapely
    - sqlalchemy >=1.3
    - thrift 0.13.0
    - packaging >=20.0
    - rbc
    - requests >=2.23.0

test:
  imports:
    - pymapd
    - omnisci
    - omnisci.serialized_result_set
    - omnisci.thrift
    - omnisci.completion_hints
    - omnisci.common

about:
  home: http://github.com/omnisci/pymapd
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.md
  summary: A python DB API 2 compatible client for OmniSci (formerly MapD).
  description: |
    A python DB API 2 compatible client for OmniSci (formerly MapD).
  doc_url: https://pymapd.readthedocs.io
  dev_url: https://github.com/omnisci/pymapd

extra:
  recipe-maintainers:
    - TomAugspurger
    - andrewseidl
    - xhochy
    - xmnlab
    - jclay
    - alexbaden
