{% set name = "pymapd" %}
{% set version = "0.7.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7fee033466ce38731912b88f7ee8a7c55cf24fa5b231c9f954d6f6bea0e6e89b

build:
  number: 1002
  noarch: python
  script: "{{ PYTHON }} -m pip install --no-deps --ignore-installed . -vvv"

requirements:
  host:
    - python
    - pip
    - setuptools_scm
    - numpy 1.14.*
    - arrow-cpp >=0.10
    - pyarrow >=0.10
  run:
    - python
    - setuptools
    - {{ pin_compatible('numpy') }}
    - arrow-cpp >=0.10,<0.12
    - pyarrow >=0.10,<0.12
    - pandas
    - six
    - sqlalchemy
    - thrift 0.11.*

test:
  imports:
    - pymapd
    - mapd

about:
  home: http://github.com/omnisci/pymapd
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.md
  summary: 'A python DB API 2 compatible client for mapd.'
  description: |
    A python DB API 2 compatible client for mapd.
  doc_url: https://pymapd.readthedocs.io
  dev_url: https://github.com/omnisci/pymapd

extra:
  recipe-maintainers:
    - TomAugspurger
    - andrewseidl
    - randyzwitch
