travis:
  secure:
    BINSTAR_TOKEN: FuAOjzVHCEG7yLBbUbmnB2Mz7qPe8TnSG18cddzoJVE0x5ftFRYKcc6U5jPu3+f1a5FaYTGAnstIp6MumJJxc7ppawa2VWl5sCWi8A6GTd4V3edrdsdFd1zUGtwpx/wWnulYTYTchL5oBjj4OuBofSL68niDA2RPJh0ijbSvJwLcxCH8dYZLBbz6Jej32IXB3CECo9eVEHIM8HQDk/8xzxrOK9dWffak05a4E4LdFdcfl2VduAV0UdtiyI0uwf1cKb08pGOH0MPajumne0VlJ9W/ClNbOlcVg6H4D15hp//dtkvbpRkpdlgZHRKZS9jezBHt6BtObd8cF2RfJ9JFIpX1DQ7d3R7CMkz6TPdyFnPcKpNZNSI5+gUvg7RGwh++GQTgjdR/zhhpQV6H7JxffyfR/z2QVWSeq5L9t/hJOaNOyAL7L6YmVbZEOsDIZo+f1ulQx5X8Dl1p7QiK+vmFpSqtC2BY4+ljkASt3GxmlNNW7LZRzZClf/P4+9wx56QrRFRMDMzcPGpMfz0ytjPAh17NoGBpreWFjnRKZI6Whu2vutaSVvOvTadu8wkG4Ie24DxOyqAxpkrOsfgZPAent8ppLywAzVzKMc8rjyL9GvY3d5DuqWz1YJlPw7mCoEOmDQ0u3/bGfF58+eQzJzTnf908krQCgn8ufE55HtXgCkM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
max_py_ver: '37'
